### ISSUE TITLE
Доработка страницы компаниям

### ISSUE THREAD

**Issue by awbait** [SoftMain/sprint-front#18]
1. Секции разделить на компоненты (Сунуть в папку Contact) и подключить их.
2. Снизу при нажатии на почту, должен отрабатывать почтовый ивент
3. Настроить работу формы. Инпуты должны быть подключены к переменным во Вью. При нажатии кнопки отправить - должна вызываться функция (слать объект введенных данных в консоль). А так же при нажатии на кнопку мы должны проверять валидность почты, и остальные введенные данные в полях (на их наличие), у почты (что это реально почта). Если все ок -> в консоль отправляем данные и очищаем инпуты.
4. ! Попробовать сделать зум картинки в мейне (не большой) (* Пока можно отложить)

**Comment by Xellan** [comment]
Всё кроме 4 пункта сделано
